# Generated by Django 5.2.7 on 2025-12-12 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_article_rank_articleimage_articlevideo_reporter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.RemoveField(
            model_name='article',
            name='video',
        ),
    ]
