# Generated by Django 5.2.7 on 2025-12-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_article_image_article_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.RemoveField(
            model_name='article',
            name='video',
        ),
        migrations.AddField(
            model_name='article',
            name='content_hindi',
            field=models.TextField(blank=True),
        ),
    ]
