# Generated by Django 5.2.7 on 2025-12-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_remove_article_image_remove_article_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content_hindi',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='article_images/'),
        ),
        migrations.AddField(
            model_name='article',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='article_videos/'),
        ),
    ]
